name: docker CI pipeline
run-name: ${{ github.actor }} is running our Docker CI Pipeline
on:
  push:
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Lint Dockerfile with Hadolint
         uses: hadolint/hadolint-action@v3.1.0
         with:
           dockerfile: Dockerfile
           ignore: DL4000

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-python:v2 .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-python:v2
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-python:v2

      - name: Run Docker container
        run: docker run --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-python:v2

      - name: View Docker containers
        run: docker ps

  k8s-implementation:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Create Deployment and Service
        run: |
          kubectl apply -f manifests/Deployment.yaml
          kubectl apply -f manifests/Service.yaml
          kubectl wait --for=condition=ready pod -l app=helloworld-python --timeout=120s

      - name: View deployment and service
        run: |
          kubectl get deployments
          kubectl get service

      - name: Test service URLs
        run: |
          minikube service list
          minikube service my-service --url
          echo "---------opening-------"
          curl $(minikube service my-service --url)
          
