name: docker CI pipeline
run-name: ${{ github.actor }} is running our Docker CI Pipeline
on: [push]
jobs:  
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
        - name: clone the code
          uses: actions/checkout@v6
          
        - name: Lint Dockerfile
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile
            ignore: DL4000
          
        - name: Docker build
          run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1 . 
          
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@v0.36.0
          with:
              image-ref: '${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v2'
              format: 'table'
              exit-code: '1'
              ignore-unfixed: true
              vuln-type: 'os,library'
              severity: 'CRITICAL,HIGH'
          
        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ vars.DOCKERHUB_TOKEN }}
            
        - name: Docker push
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-python:v2

        - name: Run Docker container
          run: docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-python:v2

        - name: View Docker container
          run: docker ps
