name: docker CI pipeline
run-name: ${{github.actor }} is running out Docker CI Pipeline
on: [push]
jobs:  
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
        - name: clone the code
          uses: actions/checkout@v6
         
        - name: Docker build
          uses: docker build -t  ${{ vars.DOCKERHUB_USERNAME }} /helloworld-python:v1 .     
      
        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Docker push
          run: docker push ${{ vars.DOCKERHUB_USERNAME }} /helloworld-python:v1

        - name: Run Docker container
          run: docker run -d -p 8080:8080 ${{ vars.DOCKERHUB_USERNAME }}/helloworld-python:v1

        - name: View Docker container
          run: docker ps           
              
